name: C_C++_CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - clang-test


jobs:
  # build:
  #   uses: NWChemEx-Project/.github/.github/workflows/parallel_build_tmpl.yaml@parallel-template
  #   with: 
  #     dependencies: 'gcc gcovr cmake openmpi clang'
  #   secrets:
  #     CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
  build-with-clang:
    uses: NWChemEx-Project/.github/.github/workflows/parallel-build-test.yaml@parallel-template
    with: 
      dependencies: 'gcovr cmake openmpi clang'
      clang-build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}

  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/parallel-build-test.yaml@parallel-template
    with: 
      dependencies: 'gcc gcovr cmake openmpi'
      clang-build: false
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}