name: C_C++_CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yml@master
    with: 
      get_dependencies_params: 'gcc gcovr cmake openmpi'