name: C_C++_CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - workflow-update

jobs:
  build:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yml@master
    with: 
      dependencies: 'gcc gcovr cmake openmpi'
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}