name: Build and Deploy Documentation
on:
  push:
    branches:
      - master
      - automate-versioning


jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/deploy_docs_tmpl.yaml@automate-versioning
    with:
      target: parallelzone_cxx_api
      dependencies: cmake doxygen graphviz sphinx
      skip_doxygen: false
