name: Build and Deploy Documentation
on:
  push:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/deploy_docs_tmpl.yml@master
    with: 
      reponame_cxx_api: parallelzone_cxx_api
      dependencies: cmake doxygen sphinx
