name: Test Documentation
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev-quazi

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yml@master
    with:
      target: parallelzone_cxx_api
      dependencies: cmake doxygen sphinx